@echo off
echo Descargando Gradle Wrapper...
powershell -Command "Invoke-WebRequest -Uri 'https://services.gradle.org/distributions/gradle-8.2-bin.zip' -OutFile 'gradle.zip'"
echo Descomprimiendo...
powershell -Command "Expand-Archive -Path 'gradle.zip' -DestinationPath '.' -Force"
ren gradle-8.2 gradle
echo Preparando el entorno...
del gradle.zip
echo Gradle configurado. Intentando compilar...
gradle\bin\gradle assembleDebug
